export const DI_TYPES = {
  TenantRepository: Symbol("TenantRepository"),
  TenantAuthService: Symbol("TenantAuthService"),
  TenantProfileService: Symbol("TenantProfileService"),
  TenantAuthController: Symbol("TenantAuthController"),
  TenantProfileController: Symbol("TenantProfileController"),
  TenantPropertyService: Symbol("TenantPropertyService"),
  TenantPropertyController: Symbol("TenantPropertyController"),
  VisitBookingRepository: Symbol("VisitBookingRepository"),
  VisitBookingService: Symbol("VisitBookingService"),
  TenantVisitController: Symbol("TenantVisitController"),
  InquiryRepository: Symbol("InquiryRepository"),
  TenantInquiryService: Symbol("TenantInquiryService"),
  WishlistRepository: Symbol.for("WishlistRepository"),
  TenantWishlistService: Symbol.for("TenantWishlistService"),

  LandlordRepository: Symbol("LandlordRepository"),
  LandlordAuthService: Symbol("LandlordAuthService"),
  LandlordKycService: Symbol("LandlordKycService"),
  LandlordProfileService: Symbol("LandlordProfileService"),
  LandlordAuthController: Symbol("LandlordAuthController"),
  LandlordProfileController: Symbol("LandlordProfileController"),
  LandlordKycController: Symbol("LandlordKycController"),
  PropertyRepository: Symbol("PropertyRepository"),
  LandlordPropertyService: Symbol("LandlordPropertyService"),
  LandlordPropertyController: Symbol("LandlordPropertyController"),
  LandlordVisitService: Symbol("LandlordVisitService"),
  LandlordVisitController: Symbol("LandlordVisitController"),
  LandlordInquiryService: Symbol("LandlordInquiryService"),

  AdminRepository: Symbol("AdminRepository"),
  AdminAuthService: Symbol("AdminAuthService"),
  AdminTenantService: Symbol("AdminTenantService"),
  AdminLandlordService: Symbol("AdminLandlordService"),
  AdminAuthController: Symbol("AdminAuthController"),
  AdminTenantController: Symbol("AdminTenantController"),
  AdminLandlordController: Symbol("AdminLandlordController"),

  RedisService: Symbol("RedisService"),
  EmailService: Symbol("EmailService"),
  AuthService: Symbol("AuthService"),
  UserRepoMap: Symbol("UserRepoMap"),
  ConversationRepository: Symbol.for("ConversationRepository"),
  MessageRepository: Symbol.for("MessageRepository"),
  ChatService: Symbol.for("ChatService"),
} as const;
